Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Linq;

namespace PORFAVORFUNCIONA3.Models
{
    public class Cliente {
        [StringLength(100, MinimumLength = 2, ErrorMessage = "O nome deve ter no mínimo 2 letras")]
        [Required(ErrorMessage = "O preenchimento do nome é obrigatório")]
        public string Nome_client { get; set; }

        [Required(ErrorMessage = "O campo é obrigatório")]
        public string CPF_client { get; set; }

        [Required(ErrorMessage = "O campo é obrigatório" )]
        public string DataDN_client{ get; set; }

        [Required(ErrorMessage = "O campo é obrigatório")]
        public string Email_client { get; set; }

        [Required(ErrorMessage = "O campo é obrigatório")]
        public Int64 Tel_client { get; set; }

        [Required(ErrorMessage = "O campo é obrigatório")]
        public string Endereco_client { get; set; }


    }
}

Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PORFAVORFUNCIONA3.Models
{
    public class Funcionario
    {
        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public int Cod_func { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string Nome_func { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string CPF_func{ get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string RG_func { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string DataDN_func { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string Endereco_func { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public int Tel_func { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string Email_func { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string Cargo_func { get; set; }

    }
}

Models/Jogo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PORFAVORFUNCIONA3.Models
{
    public class Jogo
    {
        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public int Cod_jogo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string Nome_jogo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo é obrigatório")]
        public string Versao_jogo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo desenvolvedor é obrigatório")]
        public string Dev_jogo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo gênero é obrigatório")]
        public string Genero_jogo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo faixa etaria é obrigatório")]
        public string FaixaEtaria_jogo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo plataforma é obrigatório")]
        public string Plataforma_jogo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo ano de lançamento é obrigatório")]
        public int AnodeLanc_jogo { get; set; }

        [Required(ErrorMessage = "O preenchimento do campo sinopse é obrigatório")]
        public string Sinopse_jogo { get; set; }
    }
}

Controllers/BriefController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PORFAVORFUNCIONA3.Models;

namespace PORFAVORFUNCIONA3.Controllers
{
    public class BriefController : Controller
    {
        // GET: Brief
        public ActionResult Index(){

                Jogo jogo = new Jogo();
                return View(jogo);
            }
         
        [HttpPost]

        public ActionResult Index(Jogo jogo){
            if (ModelState.IsValid) {
                return View("MostrarJogo", jogo);
            }

            return View(jogo);
        }
        
        public ActionResult MostrarJogo(Jogo jogo) {
            return View(jogo);
        }

 }}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PORFAVORFUNCIONA3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Controllers/VulcanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PORFAVORFUNCIONA3.Models;

namespace PORFAVORFUNCIONA3.Controllers
{
    public class VulcanController : Controller
    {
        // GET: Vulcan
        public ActionResult Index(){
            var cliente = new Cliente();

            return View(cliente);
        }

        [HttpPost]
        public ActionResult Index(Cliente cliente) {
            if (ModelState.IsValid) {
                return View("MostrarCliente", cliente);
            }
            return View(cliente);

        }

        public ActionResult MostrarJogo(Cliente cliente) {
            return View(cliente);
        }
        
}}

Controllers/WinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PORFAVORFUNCIONA3.Models;

namespace PORFAVORFUNCIONA3.Controllers
{
    public class WinkController : Controller
    {
        // GET: Wink
        public ActionResult Index() {
            Funcionario funcionario = new Funcionario();
            return View(funcionario);
        }

        [HttpPost]
        public ActionResult Index(Funcionario funcionario) { 
            if (ModelState.IsValid) {
                return View("MostrarFuncionario", funcionario);
            }
            return View(funcionario);
        }

        public ActionResult MostrarFuncionario(Funcionario funcionario) {
            return View(funcionario);
        }
    }
}

Views/Brief/Index.cshtml
@model PORFAVORFUNCIONA3.Models.Jogo
@{
    ViewBag.Title = "Index";
}

<h2>Cadastro do jogo:</h2>
@using (Html.BeginForm())
{

    @Html.ValidationSummary(true)
<fieldset>
    <div>
        <label for="Cod_jogo">Código do Jogo:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Cod_jogo)
        @Html.ValidationMessageFor(model => model.Cod_jogo)
    </div>

    <div>
        <label for="Nome_jogo">Nome do Jogo:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Nome_jogo)
        @Html.ValidationMessageFor(model => model.Nome_jogo)
    </div>

    <div>
        <label for="Versao_jogo">Versão:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Versao_jogo)
        @Html.ValidationMessageFor(model => model.Versao_jogo)
    </div>

    <div>
        <label for="Dev_jogo">Desevolvedor:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Dev_jogo)
        @Html.ValidationMessageFor(model => model.Dev_jogo)
    </div>

    <div>
        <label for="Genero_jogo">Gênero:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Genero_jogo)
        @Html.ValidationMessageFor(model => model.Genero_jogo)
    </div>

    <div>
        <label for="FaixaEtaria_jogo">Faixa Etária indicada:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.FaixaEtaria_jogo)
        @Html.ValidationMessageFor(model => model.FaixaEtaria_jogo)
    </div>

    <div>
        <label for="Plataforma_jogo">Plataforma em que ficará disponível:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Plataforma_jogo)
        @Html.ValidationMessageFor(model => model.Plataforma_jogo)
    </div>

    <div>
        <label for="AnodeLanc_jogo">O ano de Lançamento:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.AnodeLanc_jogo)
        @Html.ValidationMessageFor(model => model.AnodeLanc_jogo)
    </div>

    <div>
        <label for="Sinopse_jogo">Sinopse:</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Sinopse_jogo)
        @Html.ValidationMessageFor(model => model.Sinopse_jogo)
    </div>
    <br />
    <p><input type="submit" value="Cadastrar" /></p>
</fieldset>


    @section scripts{
        @Scripts.Render("~/bundles/jqueryval");
    }}

Views/Brief/MostrarJogo.cshtml
@model PORFAVORFUNCIONA3.Models.Jogo
@{
    ViewBag.Title = "MostrarJogo";
}

<h2>Dados Cadastrados:</h2>

<fieldset>
    <div>
        <label for="Cod_jogo">Código do jogo:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Cod_jogo)
    </div><br />

    <div>
        <label for="Nome_func">Nome:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Nome_jogo)
    </div><br />

    <div>
        <label for="CPF_func">Versão:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Versao_jogo)

    </div><br />

    <div>
        <label for="RG_func">Desenvolvedor</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Dev_jogo)

    </div><br />

    <div>
        <label for="DataDN_func">Gênero:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Genero_jogo)
    </div><br />

    <div>
        <label for="Endereco_func">Faixa Etária:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.FaixaEtaria_jogo)
    </div><br />

    <div>
        <label for="Tel_func">Plataforma:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Plataforma_jogo)
    </div><br />

    <div>
        <label for="Email_func">Ano de Lançamento:</label>
    </div>
    <div>
        @Html.DisplayFor(model => model.AnodeLanc_jogo)
    </div><br />

    <div>
        <label for="Cargo_func">Sinopse:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Sinopse_jogo)

    </div><hr />
    <p>@Html.ActionLink("Voltar", "Index")</p>
</fieldset>


Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Phazon", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cliente", "Index", "Vulcan")</li>
                    <li>@Html.ActionLink("Funcionario", "Index", "Wink")</li>
                    <li>@Html.ActionLink("Jogo", "Index", "Brief")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Loja de Games</p>
        
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Vulcan/Index.cshtml
@model PORFAVORFUNCIONA3.Models.Cliente
@{
    ViewBag.Title = "Index";
}

<h2>Área de cadastro do Cliente</h2>

@using (Html.BeginForm())
{

    @Html.ValidationSummary(true)
    <fieldset>
        <div>
            <label for="Nome_client">Nome:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome_client)
            @Html.ValidationMessageFor(model => model.Nome_client)
        </div>

        <div>
            <label for="CPF_client">CPF:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CPF_client)
            @Html.ValidationMessageFor(model => model.CPF_client)
        </div>

        <div>
            <label for="Versao_jogo">Data de Nascimento:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DataDN_client)
            @Html.ValidationMessageFor(model => model.DataDN_client)
        </div>

        <div>
            <label for="Dev_jogo">Email:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email_client)
            @Html.ValidationMessageFor(model => model.Email_client)
        </div>

        <div>
            <label for="Genero_jogo">Telefone:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tel_client)
            @Html.ValidationMessageFor(model => model.Tel_client)
        </div>

        <div>
            <label for="FaixaEtaria_jogo">Endereço:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Endereco_client)
            @Html.ValidationMessageFor(model => model.Endereco_client)
        </div>
        <br />
        <p><input type="submit" value="Cadastrar" /></p>
    </fieldset>


    @section scripts{
        @Scripts.Render("~/bundles/jqueryval");
    }}

Views/Vulcan/MostrarCliente.cshtml
@model PORFAVORFUNCIONA3.Models.Cliente
@{
    ViewBag.Title = "MostrarCliente";
}

<h2>Dados Cadastrados:</h2>
<fieldset>
    <div>
        <label for="Nome_client">Nome:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Nome_client)
    </div>
    <br />

    <div>
        <label for="CPF_client">CPF:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.CPF_client)
    </div>
    <br />

    <div>
        <label for="DataDN_client">Data de Nascimento:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.DataDN_client)
    </div>
    <br />

    <div>
        <label for="Email_client">Email:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Email_client)
    </div>
    <br />

    <div>
        <label for="Tel_client">Telefone:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Tel_client)
    </div>
    <br />

    <div>
        <label for="Endereco_client">Endereço:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Endereco_client)
    </div>
    <hr />
    <p>@Html.ActionLink("Voltar", "Index")</p>
</fieldset>

Views/Wink/Index.cshtml
@model PORFAVORFUNCIONA3.Models.Funcionario
@{
    ViewBag.Title = "Index";
}

<h2>Área do Funcionário</h2>
@using (Html.BeginForm())
{

    @Html.ValidationSummary(true)

    <fieldset>
        <div>
            <label for="cod_func">Código do Funcionário:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cod_func)
            @Html.ValidationMessageFor(model => model.Cod_func)
        </div>

        <div>
            <label for="nome_func">Nome:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome_func)
            @Html.ValidationMessageFor(model => model.Nome_func)
        </div>


        <div>
            <label for="CPF_func">CPF:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CPF_func)
            @Html.ValidationMessageFor(model => model.CPF_func)
        </div>


        <div>
            <label for="RG_func">RG:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RG_func)
            @Html.ValidationMessageFor(model => model.RG_func)
        </div>


        <div>
            <label for="DataDN_func">Data de Nascimento:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DataDN_func)
            @Html.ValidationMessageFor(model => model.DataDN_func)
        </div>


        <div>
            <label for="Endereco_func">Endereço:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Endereco_func)
            @Html.ValidationMessageFor(model => model.Endereco_func)
        </div>

        <div>
            <label for="Tel_func">Celular:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tel_func)
            @Html.ValidationMessageFor(model => model.Tel_func)
        </div>
        <div>
            <label for="Email_func">Email:</label>
        </div>
        <div>
            @Html.EditorFor(model => model.Email_func)
            @Html.ValidationMessageFor(model => model.Email_func)
        </div>

        <div>
            <label for="Cargo_func">Cargo:</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cargo_func)
            @Html.ValidationMessageFor(model => model.Cargo_func)
        </div>

        <br />

        <p><input type="submit" value="Cadastrar" /></p>
    </fieldset>
@section scripts{
@Scripts.Render("~/bundles/jqueryval");


}}

Views/Wink/MostrarFuncionario.cshtml
@model PORFAVORFUNCIONA3.Models.Funcionario
@{
    ViewBag.Title = "MostrarFuncionario";
}
<h2>Dados Cadastrados:</h2>

<fieldset>
    <div>
        <label for="Cod_func">Código do Funcionário:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Cod_func)
    </div><br />

    <div>
        <label for="Nome_func">Nome:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Nome_func)
    </div><br />

    <div>
        <label for="CPF_func">CPF:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.CPF_func)

    </div><br />

    <div>
        <label for="RG_func">RG:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.RG_func)

    </div><br />

    <div>
        <label for="DataDN_func">Data de Nascimento:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.DataDN_func)
    </div><br />

    <div>
        <label for="Endereco_func">Endereço:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Endereco_func)
    </div><br />

    <div>
        <label for="Tel_func">Celular:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Tel_func)
    </div><br />

    <div>
        <label for="Email_func">Email:</label>
    </div>
    <div>
        @Html.DisplayFor(model => model.Email_func)
    </div><br />

    <div>
        <label for="Cargo_func">Cargo:</label>
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.Cargo_func)

    </div><hr />
    <p>@Html.ActionLink("Voltar", "Index")</p>
</fieldset>
